/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum2;

/**
 *
 * @author WINDOWS 8.1
 */
public class ProgramAritmatika extends javax.swing.JFrame {
    String jns = "";
    int jml;
    /**
     * Creates new form ProgramAritmatika
     */
    public ProgramAritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        bil4.setVisible(false);
        bil2.setVisible(false);
        bill1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bill1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Program Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 200, 30);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 110, 30);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Opsi", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(170, 60, 190, 30);

        panel.setBackground(new java.awt.Color(0, 102, 102));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operasi"));
        panel.setLayout(null);
        panel.add(ket);
        ket.setBounds(70, 10, 170, 40);

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setText("Bilangan 2");
        panel.add(b2);
        b2.setBounds(30, 140, 110, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(150, 50, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah Bilangan");
        panel.add(jLabel6);
        jLabel6.setBounds(20, 50, 110, 30);

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setText("Bilangan 1");
        panel.add(b1);
        b1.setBounds(30, 100, 110, 30);

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setText("Bilangan 3");
        panel.add(b3);
        b3.setBounds(30, 180, 110, 30);

        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setText("Bilangan 4");
        panel.add(b4);
        b4.setBounds(30, 220, 110, 30);

        hitung.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(110, 270, 150, 30);
        panel.add(hasil);
        hasil.setBounds(60, 310, 230, 70);
        panel.add(bil4);
        bil4.setBounds(140, 220, 170, 30);
        panel.add(bil2);
        bil2.setBounds(140, 140, 170, 30);
        panel.add(bil3);
        bil3.setBounds(140, 180, 170, 30);
        panel.add(bill1);
        bill1.setBounds(140, 100, 170, 30);

        getContentPane().add(panel);
        panel.setBounds(30, 110, 330, 390);

        setBounds(0, 0, 416, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed
 public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns="Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Pengurangan")){
            jns="Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Perkalian")){
            jns="Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Pembagian")){
            jns="Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        
    }
    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
 public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(false);
            b4.setVisible(false);
            bill1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            jml = 2;
        }else if(pilihanbil.getSelectedItem().equals("3")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(false);
            bill1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            jml = 3;
        }else if(pilihanbil.getSelectedItem().equals("4")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            bill1.setVisible(true);
            bil2.setVisible(true);
            jml = 4;
        }
        
    }
    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double hsl = 0.0;
        double a1, a2, a3, a4;
        a1 = Double.parseDouble(bil4.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        a3 = Double.parseDouble(bil3.getText().toString());
        a4 = Double.parseDouble(bil4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1+a2;
                hasil.setText(""+a1+ " + "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1+a2+a3;
                hasil.setText(""+a1+ " + "+a2+ " + "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1+a2+a3+a4;
                hasil.setText(""+a1+ " + "+a2+ " + "+a3+ " + "+a4+ " = " +hsl);
            }
            
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1-a2;
                hasil.setText(""+a1+ " - "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1-a2-a3;
                hasil.setText(""+a1+ " - "+a2+ " - "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1-a2-a3-a4;
                hasil.setText(""+a1+ " - "+a2+ " - "+a3+ " - "+a4+ " = " +hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1*a2;
                hasil.setText(""+a1+ " x "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1*a2*a3;
                hasil.setText(""+a1+ " x "+a2+ " x "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1*a2*a3*a4;
                hasil.setText(""+a1+ " x "+a2+ " x "+a3+ " x "+a4+ " = " +hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1/a2;
                hasil.setText(""+a1+ " : "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1/a2/a3;
                hasil.setText(""+a1+ " : "+a2+ " : "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1/a2/a3/a4;
                hasil.setText(""+a1+ " : "+a2+ " : "+a3+ " : "+a4+ " = " +hsl);
            }
        }
        
    }//GEN-LAST:event_hitungActionPerformed
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JTextField bill1;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables
}
